name: Bento test

on: [push, pull_request, workflow_dispatch]

jobs:
  package:
    name: "Package using Bento"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Bento
        run: |
          python -m pip install --upgrade pip
          pip install git+https://github.com/greeeen-dev/zenbento.py.git
      - name: Package
        run: python -m zenbento package